### ISSUE TITLE
Issue with spotify.

### ISSUE THREAD

**Issue by face-hh** [DashCruft/Website#1]
Hello dear bhaiyai :people_hugging: , it seems like the Spotify Integration API does not work for me.

It says: Invalid API key.

Thank you, DashCruft.

**Comment by DashCruft** [comment]
Hey @face-hh,

Try adding `console.log(newAccessToken)` in the `SpotifyTokenRegen.js` file, after the line `29`
Link to [the location](https://github.com/DashCruft/Website/blob/2c1067eb3de82d54281421d4a55343c3dd2d6702/SpotifyTokenRegen.js#L29)

See what the console.log shows you. Report it here.

**Comment by DashCruft** [comment]
For reference, please confirm you have a `.env` file in your root directory with the content including these options:
(`CLIENT_ID`, `CLIENT_SECRET`, and `REFRESH_TOKEN`)

**Comment by face-hh** [comment]
Bhai how do I create a `.env` file?!

**Comment by face-hh** [comment]
:flushed: i was trolling sir why take it serious
